/*
* create user
*/
CREATE SCHEMA epicerie;
GRANT ALL PRIVILEGES ON epicerie.* TO 'formateur'@'localhost' IDENTIFIED BY 'simplon';
USE epicerie;

/*
* create table
*/

CREATE TABLE IF NOT EXISTS goods(
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(45) NOT NULL UNIQUE,
    purchase_price DECIMAL (6, 2) NOT NULL,
    selling_price DECIMAL (6, 2) NOT NULL,
    categorie_id INTEGER UNSIGNED NOT NULL,
    unit_id INTEGER UNSIGNED NOT NULL,
    CONSTRAINT fk_goods PRIMARY KEY (categorie_id, unit_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS categories(
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(45) NOT NULL UNIQUE,
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS units(
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(45) NOT NULL UNIQUE,
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE IF NOT EXISTS providers(
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(45) NOT NULL UNIQUE, 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE IF NOT EXISTS articles_providers(
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    purchase_price DECIMAL (6, 2) NOT NULL,
    good_id INTEGER UNSIGNED NOT NULL,
    provider_id INTEGER UNSIGNED NOT NULL,
    CONSTRAINT fk_articles_providers PRIMARY KEY (good_id, provider_id) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE IF NOT EXISTS movments(
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    goods_id INTEGER UNSIGNED NOT NULL,
    movment_type_id INTEGER UNSIGNED NOT NULL,
    quantity DECIMAL (6, 2) NOT NULL,
    date_time TIMESTAMP NOT NULL,
    selling_price INTEGER UNSIGNED NOT NULL,
    purchase_id INTEGER UNSIGNED NOT NULL,
    CONSTRAINT fk_movments PRIMARY KEY (good_id, movment_type_id, selling_id, purchase_id) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS purchases(
    id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    date_time TIMESTAMP NOT NULL,
    provider_id INTEGER UNSIGNED NOT NULL,
    CONSTRAINT fk_purchases PRIMARY KEY (provider_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS sellings(
    id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    date_time TIMESTAMP NOT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS movments_type(
    id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(45) NOT NULL UNIQUE,
    meaning_id INTEGER UNSIGNED NOT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS meanings(
    id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(45) NOT NULL UNIQUE,
    multiply SMALLINT NOT NULL,
    subtract SMALLINT NOT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

